### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by jhgoebbert** [jtpio/jupyterlab-topbar#19]
Hello,

I like your plugin. Perhaps it could make the logout-button of the jupyterlab/hub-extension more visible (?)
https://github.com/jupyterhub/jupyterlab-hub/issues/87

Best regards,
Jens  Henrik

**Comment by jhgoebbert** [comment]
There might be some work going on here for JupyterLab 1.0:
https://github.com/jupyterlab/jupyterlab/pull/6087

**Comment by jtpio** [comment]
Thanks @jhgoebbert, that's a good idea for a new `jupyterlab-logout-button` extension.

**Comment by jtpio** [comment]
@jhgoebbert PR https://github.com/jtpio/jupyterlab-topbar/pull/20 adds a logout button to the top area.

Is that what you had in mind? (feedback welcome!)

**Comment by jhgoebbert** [comment]
Hi jtpio,

this is great! Your screencast looks exactly like I hoped it will. This will help alot.
I will add it directly to our Jupyter installation and let you know how that works.

Best,
Jens Henrik

**Comment by jhgoebbert** [comment]
I fail to install it with
   jupyter labextension install jupyterlab-topbar-extension@0.2.0
   jupyter labextension link ./packages/jupyterlab-topbar --no-build
   jupyter labextension install ./packages/jupyterlab-logout

returns:
    src/index.ts:7:25 - error TS2307: Cannot find module 'jupyterlab-topbar'.
    7 import { ITopBar } from "jupyterlab-topbar";

Can you give me a hint?

**Comment by jtpio** [comment]
Oh you're installing it from the source.

If you are willing to wait a little, I'm planning to do a release soon.

**Comment by jhgoebbert** [comment]
No problem. I will wait for the release.

With the old release jupyterlab-topbar@0.1.1 I get the following error while installing:
jupyter labextension install jupyterlab-topbar@0.1.1 --debug
[...]
  File "/usr/local/software/jureca/Stages/Devel-2019a/software/Jupyter/2019a.1-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8-goebbert/lib/python3.6/site-packages/jupyterlab/commands.py", line 1257, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))
ValueError: "jupyterlab-topbar@0.1.1" is not a valid extension:
No `jupyterlab` key

**Comment by jtpio** [comment]
The `jupyterlab-topbar` is not a JupyterLab extension, but a package to expose the topbar interface to other extensions (which is why it's giving this error).

Have you tried to setup a development environment from the `logout-ext` branch? https://github.com/jtpio/jupyterlab-topbar/blob/logout-ext/README.md#development

**Comment by jtpio** [comment]
Just released the `jupyterlab-logout` extension. For now it is still targeting JupyterLab 1.0, so to install it:

```bash
# upgrade to JupyterLab 1.0 alpha
python -m pip install -U jupyterlab --pre

# use 'next' tag for JupyterLab 1.0 compatibility
jupyter labextension install  jupyterlab-topbar-extension@next jupyterlab-logout@next
```

I will consider doing releases for the `0.35.x` series later on.

cc @jhgoebbert

**Comment by jhgoebbert** [comment]
Great, thanks.
Unfortunately, for our installation we have to stick with the 0.35.x series for now, because it is used in production.

**Comment by jtpio** [comment]
@jhgoebbert I did a release for 0.35.x, so you can now get the extension with:

```
jupyter labextension install jupyterlab-topbar-extension jupyterlab-logout
```

Feel free to open a new issue if you have any feedback or comments you would like to share!

**Comment by jhgoebbert** [comment]
jupyterlab-logout is doing a great job! Thank you.
We added another button called "Control", which points to "hub/start"
