### ISSUE TITLE
Install with Jupyterlab 2.x.x

### ISSUE THREAD

**Issue by chengxuanw** [jtpio/jupyterlab-topbar#37]
We recently auto pull down Jupyterlab 2.0.1. and when install jupyterlab-topbar-extension, it says 
```
The extension "jupyterlab-topbar-extension" does not yet support the current version of JupyterLab.
```
Do you have plan to support Jupyterlab 2.x.x? By pinning Jupyterlab == 1.2.7 seems solve the issue.

**Comment by jtpio** [comment]
> Do you have plan to support Jupyterlab 2.x.x?

Yes! Haven't got to do it yet, but hopefully early next week!

**Comment by jtpio** [comment]
@chengxuanw the latest versions of the topbar packages (0.5.0) have now been published

**Comment by chengxuanw** [comment]
thanks.
