### ISSUE TITLE
How to order elements?

### ISSUE THREAD

**Issue by masip85** [jtpio/jupyterlab-topbar#46]
How can I give use to this array? Can it change the order of the elements at the topbar?
// Items Order
    // Ordered list of the Top Bar items
    "order": [],

**Comment by jtpio** [comment]
The order is updated when the elements are dragged and dropped. The array will look like this:

```json5
{
    // Top Bar Extension
    // jupyterlab-topbar-extension:plugin
    // Top Bar Extension
    // **********************************

    // Items Order
    // Ordered list of the Top Bar items
    "order": [
        "theme-toggle",
        "logout-button",
        "memory",
        "spacer",
        "custom-text"
    ]
}
```

The names of the elements are not documented yet, so the best would be to use the Binder link to try the extension and check the settings: https://mybinder.org/v2/gh/jtpio/jupyterlab-topbar/stable?urlpath=lab

**Comment by masip85** [comment]
Ok, drag and drop exists.... I didn't realize. Thanks

**Comment by jtpio** [comment]
No problem.

It's briefly showcased in the screencast in the README, although this screencast is a bit long so it might be easy to miss!

Closing as answered.
